services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing-node
    hostname: ${HOSTNAME} 
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/config 
      - ${MEDIA_VAULT}/media-vault-in:/config/media-vault-in
      - ${MEDIA_VAULT}/media-vault-out:/config/media-vault-out
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
